
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_DOCTORS = "GET_DOCTORS"
export const ADD_DOCTORS = "ADD_DOCTORS"
export const DELETE_DOCTORS = "DELETE_DOCTORS"
export const UPDATE_DOCTORS = "UPDATE_DOCTORS"
export const LOADING_DOCTORS = "LOADING_DOCTORS"
export const ERROR_DOCTORS = "ERROR_DOCTORS"

export const GET_MEDICINE = "GET_MEDICINE"
export const ADD_MEDICINE = "ADD_MEDICINE"
export const DELETE_MEDICINE = "DELETE_MEDICINE"
export const UPDATE_MEDICINE = "UPDATE_MEDICINE"
export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const ERROR_MEDICINE = "ERROR_MEDICINE"

export const GET_DEPARTMENT = "GET_DEPARTMENT"
export const ADD_DEPARTMENT = "ADD_DEPARTMENT"
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"
export const LOADING_DEPARTMENT = "LOADING_DEPARTMENT"
export const ERROR_DEPARTMENT = "ERROR_DEPARTMENT"

export const ADD_TO_CART = "ADD_TO_CART"
export const INC_QTY = "INC_QTY"
export const DEC_QTY = "DEC_QTY"
export const REMOVE_ITEM = "REMOVE_ITEM"

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE"
export const REMOVE_TO_FAVORITE = "REMOVE_TO_FAVORITE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_IN = "LOGIN_IN"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT = "LOGOUT"
export const FORGET_REQUSET = "FORGET_REQUSET"
export const AUTH_ERROR = "AUTH_ERROR"


  